// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heuzrmmeeebjqiotavbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhldXpybW1lZWVianFpb3RhdmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDMzMjksImV4cCI6MjA1ODA3OTMyOX0.f1Ie3GCa86sVIWC4ho5NdRjp4GdcPY5wTTeMPVtVtHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);